### ISSUE TITLE
Backend changes for new UI

### ISSUE THREAD

**Issue by a-martynovich** [WoTTsecurity/api#616]
- [x] On every page there needs to be "Current Trust Score" and "Actions Solved"
- [x] "Actions Solved" is how many RAs were solved since his week's Monday
- [x] #591 - need last week's average of average trust score
- [x] #591 - need short RA texts written out in subtasks of WoTTsecurity/wott-io#198
- [x] #596 - need a count of high, med and low CVEs and a max of high, med, low CVEs since Monday (need additional history element for this) and since last week's Monday
- [x] #615 - an endpoint to check node list length periodically. Could be made using an already existing endpoint with HEAD request.
~~* #591, 594 - solved RAs should appear too~~ - TBD
~~* #591 - need dummy RA list for the "Welcome" state (when Node List is empty)~~ - just use placeholders
